# Generated by Django 5.1.6 on 2025-02-22 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdfdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?[\\d\\-x\\.()]+$')]),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])]),
        ),
    ]
